version: "3.9"
services:
  ecocontrol:
    build: .
    image: ecocontrol:latest
    container_name: ecocontrol
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: dev
      # SPRING_DATASOURCE_URL: jdbc:oracle:thin:@oracle.fiap.com.br:1521:ORCL
      # SPRING_DATASOURCE_USERNAME: RM556387
      # SPRING_DATASOURCE_PASSWORD: 100590
    restart: unless-stopped